### ISSUE TITLE
Add support for git tags

### ISSUE THREAD

**Issue by vsudilov** [adsabs/mission-control#11]
In general, need to decide if we "support" tags or if that is the core mechanism the triggers builds.
- `models.py` need the proper field.
- `manage.py:Build` needs to be able to query the github api by tag or commit
- `GithubListener` should look for tags instead of (in addition to?) `head_commit`

**Comment by romanchyla** [comment]
since tags are made (by the developer) only for releases
and there is always more commits than tags
but commits are not deployed (releases are)
and builds take non-negligible time
then it would make sense to make releases be the 'trigger'
